esphome:
  name: newswim
  platform: ESP8266
  board: d1_mini
  on_boot:
    priority: 100
    then:
      switch.turn_on: switch_pwr_en
  on_shutdown:
    then:
      switch.turn_off: switch_pwr_en

substitutions:
  display_name: DIY_Solar_1
  
# Enable logging
logger:
  level: debug

ota:
  password: "3f70769bcab7af3d104a2bcac4017cd7"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Swimming-Pool Fallback Hotspot"
    password: !secret wifi_password

captive_portal:

switch:
  - platform: gpio
    pin: D4
    id: switch_pwr_en
    
time:
  - platform: sntp
    id: sntp_time
    timezone: America/Los_Angeles
    on_time:
      - hours: 11  # 1 hour
        then:
        - lambda: |-
              id(deep_sleep_1).set_sleep_duration(3600000); 
      - hours: 17 # 5 minutes
        then:
        - lambda: |-
              id(deep_sleep_1).set_sleep_duration(300000); 
      - hours: 23 # 1 hour
        then:
        - lambda: |-
              id(deep_sleep_1).set_sleep_duration(3600000); 
    
mqtt:
  broker: "192.168.68.99"
  username: "yourMQTT"
  password: "yourMQTTpass"
  birth_message: #Setting the MQTT Birth and Will message to blank stops the device from going Unavailable while it is asleep which messes with history graphs (lots of dots/broken lines)
  will_message:
  on_message:
    - topic: ${display_name}/ota_mode
      payload: 'ON'
      then:
        - deep_sleep.prevent: deep_sleep_1
    - topic: ${display_name}/sleep_mode
      payload: 'ON'
      then:
        - deep_sleep.enter: deep_sleep_1

#Deep sleep
deep_sleep:
  run_duration: 70s
  sleep_duration: 1min
  id: deep_sleep_1
  
dallas:
  - pin: D1
    id: dallas_1
    update_interval: 30s

sensor:
  - platform: dallas
    address: 0xD23C01E076358A28
    name: "Swimming Pool temp"
    id: dallas_temp_1
  - platform: dallas
    address: 0x0255890D1E64FF28
    name: "Jacuzzi"
    id: dallas_temp_2
#  - platform: dht
#    pin: D2
#    temperature:
#      name: "Internal Temp"
#    humidity:
#      name: "Internal Humidity"